apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mrtk-tracker
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 544.0.0
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: mrtk-tracker
        image: asia-northeast3-docker.pkg.dev/mrtk-tracker/cloud-run-source-deploy/mrtk-tracker/mrtk-tracker:2a491cc3ad1311a038291adb193a392364bc802a
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
