apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mrtk-tracker
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 544.0.0
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: mrtk-tracker
        # ✅ Cloud Build에서 sed로 치환됨 (자동 IMAGE 변수 제거)
        image: asia-northeast3-docker.pkg.dev/$PROJECT_ID/mrtk-tracker/mrtk-tracker:$COMMIT_SHA
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi # 1GB 할당 (필요에 따라 2Gi 등으로 늘릴 수 있음)
  traffic:
  - percent: 100
    latestRevision: true
